# Generated by Django 3.2 on 2024-09-24 15:34

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text=('Required. 150 characters or fewer.', 'Letters, digits and @/./+/-/_ only.'), max_length=150, unique=True, validators=[users.validators.UsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
