# Generated by Django 3.2 on 2024-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240919_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(db_column='password', default=1, max_length=128),
            preserve_default=False,
        ),
    ]
